export const CarpetStyles = [
	{ style: '17th Century Rugs' },
	{ style: 'Afghan Rugs' },
	{ style: 'African Kuba Textiles' },
	{ style: 'Afshar Rugs' },
	{ style: 'Agra Rugs' },
	{ style: 'Alcaraz Rugs' },
	{ style: 'Alpujarra Rugs' },
	{ style: 'Amoghli Carpets' },
	{ style: 'Amritsar Rugs' },
	{ style: 'Angora Rugs' },
	{ style: 'Art Deco Chinese Rugs' },
	{ style: 'Art Nouveau Rugs' },
	{ style: 'Arts And Crafts Rugs' },
	{ style: 'Aubusson Rugs' },
	{ style: 'Avar Rugs' },
	{ style: 'Axminster Carpets' },
	{ style: 'Bakhtiari Rugs' },
	{ style: 'Bakshaish Serapi Heriz Rugs' },
	{ style: 'Baluch Rugs' },
	{ style: 'Bergama Rugs' },
	{ style: 'Beshir Carpets' },
	{ style: 'Bessarabian Carpets' },
	{ style: 'Bezalel Rugs' },
	{ style: 'Bibikabad Rugs' },
	{ style: 'Bidjar Rugs' },
	{ style: 'Bokara Rugs' },
	{ style: 'Borchalou Kazak Rugs' },
	{ style: 'Cairene Rugs' },
	{ style: 'Chenille Rugs' },
	{ style: 'Chi Chi Rugs' },
	{ style: 'Chinese Rank Badges' },
	{ style: 'Chinese Rugs' },
	{ style: 'Continental Rugs' },
	{ style: 'Cuenca Rugs' },
	{ style: 'Dagestan Rugs' },
	{ style: 'Dalmatic Textiles' },
	{ style: 'Donegal Carpets' },
	{ style: 'Eagle Kazak Rugs' },
	{ style: 'Ege Rugs' },
	{ style: 'English Rugs' },
	{ style: 'Ersari Rugs' },
	{ style: 'Ewe Kente Cloth Textiles' },
	{ style: 'Farahan Rugs' },
	{ style: 'Gabbeh Rugs' },
	{ style: 'Gashgai Qashqai Rugs' },
	{ style: 'Greek Textiles' },
	{ style: 'Hamedan Rugs' },
	{ style: 'Hereke Carpets' },
	{ style: 'Heriz' },
	{ style: 'Serapi' },
	{ style: 'Bakshaish Rugs' },
	{ style: 'Hooked Rugs' },
	{ style: 'Horse Covers' },
	{ style: 'Ikat Textiles' },
	{ style: 'Indian Rugs' },
	{ style: 'Ingrain Rugs' },
	{ style: 'Isfahan Carpets' },
	{ style: 'Jajim' },
	{ style: 'Judaica Rugs' },
	{ style: 'Kaitag Embroideries Textiles' },
	{ style: 'Kansu Rugs' },
	{ style: 'Karabagh Rugs' },
	{ style: 'Karachopf Rugs' },
	{ style: 'Karakashly Rugs' },
	{ style: 'Karapinar Rugs' },
	{ style: 'Kars Rugs' },
	{ style: 'Kashan Rugs' },
	{ style: 'Kayseri Rugs' },
	{ style: 'Kazak Rugs' },
	{ style: 'Kerman Carpets' },
	{ style: 'Khorassan Rugs' },
	{ style: 'Khotan Carpets' },
	{ style: 'Kirshehir Carpets' },
	{ style: 'Konya Rugs' },
	{ style: 'Kuba Rugs' },
	{ style: 'Kula Rugs' },
	{ style: 'Kurdish Rugs' },
	{ style: 'Ladik Rugs' },
	{ style: 'Lilihan Rugs' },
	{ style: 'Lori Rugs' },
	{ style: 'Malayer Rugs' },
	{ style: 'Marbediah Rugs' },
	{ style: 'Mashahir Rugs' },
	{ style: 'Mazandaran Kilims' },
	{ style: 'Milas Melas Rugs' },
	{ style: 'Mishan Rugs' },
	{ style: 'Mongolian Rugs' },
	{ style: 'Moroccan Rugs' },
	{ style: 'Mughal Rugs' },
	{ style: 'Nain Rugs' },
	{ style: 'Navajo Rugs' },
	{ style: 'NeedlePoint Rugs' },
	{ style: 'Nepalese Rugs' },
	{ style: 'North West Persian Rugs' },
	{ style: 'Oriental Rugs' },
	{ style: 'Ottoman Embroidery Textiles' },
	{ style: 'Oushak Rugs' },
	{ style: 'Paule Leleu Jules Leleu Rugs' },
	{ style: 'Peking Rugs' },
	{ style: 'Perpedil Rugs' },
	{ style: 'Peruvian Rugs' },
	{ style: 'Polonaise Rugs' },
	{ style: 'Pop Art Rugs' },
	{ style: 'Prayer Rug' },
	{ style: 'Qum Rugs' },
	{ style: 'Rya Rugs' },
	{ style: 'Samarkand Rugs' },
	{ style: 'Sarouk Farahan Rugs' },
	{ style: 'Sarouk Rugs' },
	{ style: 'Savonnerie Carpets' },
	{ style: 'Scandinavian Rugs' },
	{ style: 'Serab Rugs' },
	{ style: 'Serapi Rugs' },
	{ style: 'Seychour Rugs' },
	{ style: 'Shasavan Shasevan Rugs' },
	{ style: 'Shawls' },
	{ style: 'Shirvan Rugs' },
	{ style: 'Silk Persian Rugs' },
	{ style: 'Sivas Rugs' },
	{ style: 'Smyrna Rugs' },
	{ style: 'Souf Rugs' },
	{ style: 'Soumak Rugs' },
	{ style: 'Sultanabad Rugs' },
	{ style: 'Suzani Textiles' },
	{ style: 'Tabriz Rugs' },
	{ style: 'Talish Rugs' },
	{ style: 'Textiles and Embroideries' },
	{ style: 'Tibetan Rugs' },
	{ style: 'Transylvanian Rugs' },
	{ style: 'Tuduc Rugs' },
	{ style: 'Turkish Kilims' },
	{ style: 'Vintage Shag Rugs' },
	{ style: 'Wilton Rugs' },
	{ style: 'Yarkand Rugs' },
	{ style: 'Yastic Rugs' },
	{ style: 'Yomut rugs' },
	{ style: 'Yuruk Rugs' },
	{ style: 'Zakatala Rugs' },
];
